apiVersion: v1
kind: Service
metadata:
  name: terrain-service
spec:
  type: NodePort
  ports:
    - name: http
      port: 8080
      targetPort: 8080
      nodePort: 30080
    - name: ssh
      port: 22
      targetPort: 22
      nodePort: 30022
    - name: mysql
      port: 3306
      targetPort: 3306
      nodePort: 30306
  selector:
    app: terrain-app
